{
  "7aaa128148c91fa43eff8f01ef4bf52b" : {
    "statistic" : {
      "failed" : 1,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "74c0ca0b2e994a31",
      "reportUrl" : "../15/index.html#testresult/74c0ca0b2e994a31",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000118BAB7C160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608646680866,
        "stop" : 1608646680866,
        "duration" : 0
      }
    }, {
      "uid" : "83b501389d436ba2",
      "reportUrl" : "../14/index.html#testresult/83b501389d436ba2",
      "status" : "failed",
      "statusDetails" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0",
      "time" : {
        "start" : 1608194044768,
        "stop" : 1608194048980,
        "duration" : 4212
      }
    }, {
      "uid" : "ed19fbb2daeaa862",
      "reportUrl" : "../13/index.html#testresult/ed19fbb2daeaa862",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271C0006EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608193851297,
        "stop" : 1608193851297,
        "duration" : 0
      }
    } ]
  },
  "8dc9707043572ab9df1754ba765d30ac" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 2,
      "skipped" : 0,
      "passed" : 1,
      "unknown" : 0,
      "total" : 3
    },
    "items" : [ {
      "uid" : "e224e0e3ee35ade6",
      "reportUrl" : "../15/index.html#testresult/e224e0e3ee35ade6",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017A082CC100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608646680866,
        "stop" : 1608646680866,
        "duration" : 0
      }
    }, {
      "uid" : "29d724d55ed37a78",
      "reportUrl" : "../14/index.html#testresult/29d724d55ed37a78",
      "status" : "passed",
      "time" : {
        "start" : 1608194044778,
        "stop" : 1608194048978,
        "duration" : 4200
      }
    }, {
      "uid" : "4918ab8d3e271240",
      "reportUrl" : "../13/index.html#testresult/4918ab8d3e271240",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DF09109F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608193851297,
        "stop" : 1608193851297,
        "duration" : 0
      }
    } ]
  }
}