{
  "uid" : "125525cc6801424c",
  "name" : "Пользователь может осуществить поиск (failed)",
  "fullName" : "tests.test_main_page#test_guest_can_go_to_checkout_failed",
  "historyId" : "7aaa128148c91fa43eff8f01ef4bf52b",
  "time" : {
    "start" : 1608647413081,
    "stop" : 1608647416157,
    "duration" : 3076
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0",
  "statusTrace" : "browser = <selenium.webdriver.remote.webdriver.WebDriver (session=\"24fc9246fbe3843b52293ec33afb90d3\")>\npage = <pages.main_page.MainPage object at 0x000001C3BD774AF0>\n\n    @allure.title('Пользователь может осуществить поиск (failed)')\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_guest_can_go_to_checkout_failed(browser, page):\n        with allure.step('Ввод запроса и нажатие кнопки \"Поиск в Google\"'):\n            page.enter_search_query(\"МТС\")\n            page.click_search_button()\n        with allure.step('Проверка, что первый результат соответствует ожиданиям'):\n            results_page = ResultsPage(browser, links.MAIN_PAGE)\n>           results_page.should_has_result_with_correct_title(0, \"МТС - связь и экосистема цифровых сервисов failed\")\n\ntests\\test_main_page.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.results_page.ResultsPage object at 0x000001C3BD7B0E80>\nresult_number = 0\nresult_title = 'МТС - связь и экосистема цифровых сервисов failed'\n\n    def should_has_result_with_correct_title(self, result_number, result_title):\n>       assert self.browser.find_elements(*ResultPageLocators.RESULTS)[result_number].text.find(result_title) != -1, f\"{result_title} is not presented in result number {result_number}\"\nE       AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0\n\npages\\results_page.py:7: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "page",
    "time" : {
      "start" : 1608647410672,
      "stop" : 1608647413075,
      "duration" : 2403
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Открываем https://www.google.com/",
      "time" : {
        "start" : 1608647410673,
        "stop" : 1608647413075,
        "duration" : 2402
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1608647404521,
      "stop" : 1608647404657,
      "duration" : 136
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1608647404657,
      "stop" : 1608647410671,
      "duration" : 6014
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Запускаем браузер",
      "time" : {
        "start" : 1608647404657,
        "stop" : 1608647410411,
        "duration" : 5754
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0",
    "statusTrace" : "browser = <selenium.webdriver.remote.webdriver.WebDriver (session=\"24fc9246fbe3843b52293ec33afb90d3\")>\npage = <pages.main_page.MainPage object at 0x000001C3BD774AF0>\n\n    @allure.title('Пользователь может осуществить поиск (failed)')\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_guest_can_go_to_checkout_failed(browser, page):\n        with allure.step('Ввод запроса и нажатие кнопки \"Поиск в Google\"'):\n            page.enter_search_query(\"МТС\")\n            page.click_search_button()\n        with allure.step('Проверка, что первый результат соответствует ожиданиям'):\n            results_page = ResultsPage(browser, links.MAIN_PAGE)\n>           results_page.should_has_result_with_correct_title(0, \"МТС - связь и экосистема цифровых сервисов failed\")\n\ntests\\test_main_page.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.results_page.ResultsPage object at 0x000001C3BD7B0E80>\nresult_number = 0\nresult_title = 'МТС - связь и экосистема цифровых сервисов failed'\n\n    def should_has_result_with_correct_title(self, result_number, result_title):\n>       assert self.browser.find_elements(*ResultPageLocators.RESULTS)[result_number].text.find(result_title) != -1, f\"{result_title} is not presented in result number {result_number}\"\nE       AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0\n\npages\\results_page.py:7: AssertionError",
    "steps" : [ {
      "name" : "Ввод запроса и нажатие кнопки \"Поиск в Google\"",
      "time" : {
        "start" : 1608647413081,
        "stop" : 1608647415970,
        "duration" : 2889
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Проверка, что первый результат соответствует ожиданиям",
      "time" : {
        "start" : 1608647415970,
        "stop" : 1608647416154,
        "duration" : 184
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0\n",
      "statusTrace" : "  File \"C:\\example_ui_tests\\tests\\test_main_page.py\", line 36, in test_guest_can_go_to_checkout_failed\n    results_page.should_has_result_with_correct_title(0, \"МТС - связь и экосистема цифровых сервисов failed\")\n  File \"C:\\example_ui_tests\\pages\\results_page.py\", line 7, in should_has_result_with_correct_title\n    assert self.browser.find_elements(*ResultPageLocators.RESULTS)[result_number].text.find(result_title) != -1, f\"{result_title} is not presented in result number {result_number}\"\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "browser::0",
    "time" : {
      "start" : 1608647416471,
      "stop" : 1608647417966,
      "duration" : 1495
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Закрываем браузер",
      "time" : {
        "start" : 1608647417907,
        "stop" : 1608647417965,
        "duration" : 58
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ {
      "uid" : "a0f817a1bbbe2195",
      "name" : "test_guest_can_go_to_checkout_failed",
      "source" : "a0f817a1bbbe2195.png",
      "type" : "image/png",
      "size" : 299853
    } ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_main_page"
  }, {
    "name" : "host",
    "value" : "DESKTOP-4VE46VG"
  }, {
    "name" : "thread",
    "value" : "2360-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_main_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "f7a5dfe9706b6638",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000118BAB7C160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608646680866,
        "stop" : 1608646680866,
        "duration" : 0
      }
    }, {
      "uid" : "64385ecfda00e661",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F3BB18DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608646176354,
        "stop" : 1608646176354,
        "duration" : 0
      }
    }, {
      "uid" : "9e2c75b41a9dcfb9",
      "status" : "failed",
      "statusDetails" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0",
      "time" : {
        "start" : 1608194044768,
        "stop" : 1608194048980,
        "duration" : 4212
      }
    }, {
      "uid" : "f3296ff3d5c33572",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000252C7998A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608193946343,
        "stop" : 1608193946343,
        "duration" : 0
      }
    }, {
      "uid" : "3af165417b789c9e",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271C0006EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "time" : {
        "start" : 1608193851297,
        "stop" : 1608193851297,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 2,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "74c0ca0b2e994a31",
        "reportUrl" : "../15/index.html#testresult/74c0ca0b2e994a31",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000118BAB7C160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
        "time" : {
          "start" : 1608646680866,
          "stop" : 1608646680866,
          "duration" : 0
        }
      }, {
        "uid" : "83b501389d436ba2",
        "reportUrl" : "../14/index.html#testresult/83b501389d436ba2",
        "status" : "failed",
        "statusDetails" : "AssertionError: МТС - связь и экосистема цифровых сервисов failed is not presented in result number 0",
        "time" : {
          "start" : 1608194044768,
          "stop" : 1608194048980,
          "duration" : 4212
        }
      }, {
        "uid" : "ed19fbb2daeaa862",
        "reportUrl" : "../13/index.html#testresult/ed19fbb2daeaa862",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271C0006EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
        "time" : {
          "start" : 1608193851297,
          "stop" : 1608193851297,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "125525cc6801424c.json",
  "parameterValues" : [ ]
}